name: Backend CI

on:
  push:
    paths:
      - '**'
    branches: [ main ]
  pull_request:
    paths:
      - '**'
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
    ## Currently not running tests
    # - name: Run tests
    #   run: |
    #     pytest
    - name: Run pre-commit hooks
      run: |
        pre-commit run --all-files
